dependencies:
  - name: oauth2-proxy
    version: 0.11.0
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: nginx-ingress
    version: 1.4.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: nginx-ingress.enabled